### ISSUE TITLE
Add a proper header/navbar in the main page 

### ISSUE THREAD

**Issue by debck** [publiclab/simple-data-grapher#105]
Note:- **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Describe the idea or (feature)

We need to add a proper header/navbar to the main page and provide some general information in it like the GitHub repo link and a bit about the application.

### Reference 

Take reference from this: https://beta.sequencer.publiclab.org/

Thank You 😊

**Comment by debck** [comment]
**Uploaded to dashboard**

**Comment by SidharthBansal** [comment]
Published

**Comment by Ryan10145** [comment]
I am currently working on this (I claimed the respective task on the GCI dashboard).
