### ISSUE TITLE
Add a footer to the page

### ISSUE THREAD

**Issue by debck** [publiclab/simple-data-grapher#106]
Note:- **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Describe the idea or (feature)

We need to add a footer to the main page and provide some general information on it.

### Reference 

We can take a reference from this: https://beta.sequencer.publiclab.org/

![reference](https://user-images.githubusercontent.com/24359/52802236-8a27f400-304d-11e9-8e1c-c7f8d83cf369.png)
Thank You 😊

**Comment by debck** [comment]
**Uploaded to GCI dashboard**

**Comment by SidharthBansal** [comment]
PUBLISHED

**Comment by genesis331** [comment]
Hi, please review the [PR](https://github.com/publiclab/community-toolbox/pull/295) made.

**Comment by genesis331** [comment]
Please review https://github.com/publiclab/simple-data-grapher/pull/110.
