### ISSUE TITLE
Refactor html to follow standard structure

### ISSUE THREAD

**Issue by debck** [publiclab/simple-data-grapher#107]
Note:- **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### What's the problem (or idea)

The HTML code we have in our project doesn't follow the standard structure. Now, we have two HTML files -
1. https://github.com/publiclab/simple-data-grapher/blob/main/index.html
2. https://github.com/publiclab/simple-data-grapher/blob/main/examples/index.html

### What should be done?
You need to refactor it to follow the standard basic structure with all the tags like `html` `head` `title` `body` etc.

Thank You 😊

**Comment by debck** [comment]
**Uploaded to GCI dashborad**

**Comment by SidharthBansal** [comment]
Published

**Comment by chen-robert** [comment]
Could I have this task assigned to me please?
