### ISSUE TITLE
Add Framework for testing

### ISSUE THREAD

**Issue by namangupta01** [publiclab/simple-data-grapher#11]
We need to add testing framework so that we write tests along with the writing code.
What do you guys say @jywarren and @IshaGupta18 ?

**Comment by namangupta01** [comment]
I am thinking of adding testing framework `mocha` and `chai` which is an assertion library for the assertion.

**Comment by IshaGupta18** [comment]
Sure absolutely, that will be needed in the long run. Please let me know when we begin testing so that I can also learn and write tests because I have rarely done it and would love to learn!
