### ISSUE TITLE
Update tests to pass Travis CI build

### ISSUE THREAD

**Issue by debck** [publiclab/simple-data-grapher#118]
Note: **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### What's the problem (or idea)
The Travis CI build for the project fails due to the recent updates in the UI of the project. 

### What should be done?

You need to update these two test cases, to help pass the CI build.

https://github.com/publiclab/simple-data-grapher/blob/94bc33c2f5a8b26c155536e0c0ab2a66bd7797ae/spec/js/ui_tests.js#L30-L37

### Reference 

You can check the recent failed build log here: https://travis-ci.com/publiclab/simple-data-grapher/builds/141074484

Thank You 😊

**Comment by debck** [comment]
**Uploaded to GCI dashboard**

**Comment by SidharthBansal** [comment]
Published

**Comment by Uzay-G** [comment]
Hey! I've solved this on my local branch but am waiting for another task to be approved. Should I make a PR when I am done with the other one?
Thanks @debck :smile:

**Comment by debck** [comment]
Yes sure @Uzay-G.

**Comment by Uzay-G** [comment]
You can check out the travis on my repo branch with my changes here: https://travis-ci.org/Uzay-G/simple-data-grapher. 

I will make a pr when I am finished.
Thanks

**Comment by debck** [comment]
Yes, good work @Uzay-G  :tada:
Remember to claim it on GCI and submit for review soon. If anyone else claims the task, then we have to give this issue to him/her.
