### ISSUE TITLE
Add test case for the footer

### ISSUE THREAD

**Issue by debck** [publiclab/simple-data-grapher#119]
Note: **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### What's the idea (or problem)

There have been recent updates in the UI of the project. We have our footer added recently. So it will be good to add a UI test for that.

### What should be done?

You need to add test cases for the footer in this file. It includes all the UI test cases.

https://github.com/publiclab/simple-data-grapher/blob/main/spec/js/ui_tests.js

Thank You 😊

**Comment by debck** [comment]
**Uploaded to dashboard**

**Comment by SidharthBansal** [comment]
Published

**Comment by CodeSarthak** [comment]
Hey, I have never written tests before. Can someone guide me as to how to proceed and how to implement the same?

Thank you.

**Comment by Uzay-G** [comment]
Hey! I would like to work on this when my other pr is accepted. Are you doing this one @CodeSarthak?
Thanks.

**Comment by CodeSarthak** [comment]
I have not claimed it yet but I was planning to do it after I complete the issue I am currently working on.
