### ISSUE TITLE
Carousel for Design 

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/simple-data-grapher#12]
I was thinking of using a bootstrap carousel, for this design (to navigate between the 3 tabs), as it might look elegant and will be easy to maintain:

![image](https://user-images.githubusercontent.com/40794215/57446473-5afed880-7272-11e9-9a81-689b3c25a594.png)

What are your views on this @namangupta01 @jywarren ?

**Comment by namangupta01** [comment]
I think we can focus on the design part later. For now, we can work on basic functionality as Jeff said here.

**Comment by IshaGupta18** [comment]
Okay!

**Comment by jywarren** [comment]
Isha has very good design ideas! Once the basics are in place, perhaps that's one way work can be divided and happen in parallel, with Isha developing designs that can be integrated later in the process!

**Comment by IshaGupta18** [comment]
Oh thanks a lot! That would be great, will work on it once we have the
basic functionality ready! You can have a look at #15 for some new work in
progess! Thanks again!

**Comment by IshaGupta18** [comment]
Okay since the basic functionality of uploading a CSV, selecting columns and viewing a graph is up at # 18, with a few refinements I think we need to move to this design part to separate the 3 steps as everything is on a single page for now. What do you think?
