### ISSUE TITLE
Not drawing correct result

### ISSUE THREAD

**Issue by keshav234156** [publiclab/simple-data-grapher#123]
I was using simple-data-Grapher with this CSV file  
https://docs.google.com/spreadsheets/d/19uWUjECy6RsdaFgZutU0lEqBCih6HLuzLVK3qAfndxI/edit?usp=sharing.
i wanted to have a graph between dates and rain column. I expected the graph to be continuous. On the x-axis, it only takes some value and on the y-axis, it taking all the values that why I think it's happening.
![newplot (1)](https://user-images.githubusercontent.com/45951376/72660699-09107400-39f7-11ea-9ac8-16a8487d4fe8.png)

why that happening?

**Comment by keshav234156** [comment]
cc:@jywarren @IshaGupta18

**Comment by IshaGupta18** [comment]
Did you try zooming the graph? This is really odd :(
