### ISSUE TITLE
Enable multiple charts using multiple csv

### ISSUE THREAD

**Issue by namangupta01** [publiclab/simple-data-grapher#25]
I think we now have a somewhat basic structure of this library. I think we can now enable multiple chart support for multiple CSVs.

**Comment by namangupta01** [comment]
I am working on this. Please feel free to provide some suggestions on this. @jywarren @IshaGupta18

**Comment by IshaGupta18** [comment]
Yes that would be great, let's fix this one together. Also, firstly, you'll
have to merge the PRs for toggle design and the add graph one to take a
pull.

**Comment by namangupta01** [comment]
Toggle pr is not dependent on this. I guess both are independent.

**Comment by namangupta01** [comment]
Let's wait for what @jywarren thinks on that pr?

**Comment by IshaGupta18** [comment]
Yes, but it would be good to merge them both if you feel it's right, but
the add graph one has to be merged anyways

**Comment by IshaGupta18** [comment]
I didn't realize this was a separate issue altogether! So could you please flesh out what exactly are we gonna do here? Will we be accepting multiple files in one go or one by one?

**Comment by jywarren** [comment]
Hi, just seeing this conversation didn't finish before we implemented it...

I worry that we are getting a little ahead of ourselves -- we may make the right choices, but for example, in ImageSequencer, we early on wanted it to handle multiple images. Then, a year later, we realized if you want multiple images, just start multiple sequencers -- it vastly simplified the code. 

So, I'm not saying that's the case here. But I do think we should take care to think through this -- even to the point of doing a few rough mockups -- with a big feature like this. 

I could imagine that you can drag in a CSV. Then once you have graphed it, you drag in a second one. Then, it adds a new graph. But why didn't we just tell people to use a second instance entirely? Do the graphs overlay? Let's figure this out carefully and be sure the reasoning is clear among @IshaGupta18 and @namangupta01. Does this make sense? 

Thanks all! You're doing great!

**Comment by IshaGupta18** [comment]
Yes, I had similar doubts when I saw its working in the GIF because I am not entirely convinced that adding another CSV file there would be able to help the user productively. We definitely need the classes, however, for another file, the user can upload it and create a fresh set of graphs with it, instead of mixing it up with another CSV, because it would be easier for them to follow. This feature can come in handy when the user wants one graph from one file and one from the other, however, we will need to create a comparison feature for that ie. We will need to design our UI in such a way that the user is able to upload multiple files and plot the graphs and do a comparison more easily, replicating the entire thing one below the other will not serve the right purpose. We sure can merge the PR and continue our work in enhancing this feature to a more useful one. What do you all think? @jywarren @namangupta01

**Comment by jywarren** [comment]
Let's think through the possible use cases. I agree with merging but this will inform our next steps.

1. 2 CSVs of the same timeframe (with timestamps and/or without)
2. 2 unrelated CSVs -- no common columns (this would not be ideal in the same instance, but people might do it anyways, so we'd have to think of how the project would respond to this)
3. 2 CSVs with one common column... for someone trying to join them and view together? This could be hard...

**Comment by namangupta01** [comment]
Hi @jywarren, in the current implementation of the library as the multiple graph pr is not merged we cannot create multiple graphs infact the code is very rigid to one csv and also we cannot create more than one instance as you can see in the code. It needs structuring of the whole code into the classes which not only gives us the organized code but also gave us the feature to have multiple instances.

**Comment by namangupta01** [comment]
In the earlier code not only user was not able to create multiple graphs but for making a graph he have to add css and html in the code with is not good. User experience should be such that he is able to do all the things by just calling a function. What do you think @jywarren?

**Comment by namangupta01** [comment]
In the current Implementation user can create as many instance he want by just calling a function and pass id of an element as argument. Doesn't this make sense? @jywarren and @IshaGupta18 and Isha we are not making comparision graph I think you mis understood, both are independent instance and we are not replicating things one below other infact we can use it anywhere in the page.

**Comment by jywarren** [comment]
Ah, can you try to illustrate this with a sketch? I think I'm not 100% sure
I'm imagining the right thing. Thanks!

**Comment by IshaGupta18** [comment]
Yes that would be great. Also, in the current implementation, we can create
multiple graphs from the same CSV very easily, which serves it's own
purpose very well.

**Comment by IshaGupta18** [comment]
And what I mean by "comparison graph" is that we can use this feature, to enable the user to plot 2 different graphs from 2 different CSVs (ie create multiple instances) and compare them by looking or through the analysis we provide. That would be a good application of this I think. What do you say?

**Comment by namangupta01** [comment]
Let's do further discussion in a new issue. This feature is implemented in #29.

**Comment by namangupta01** [comment]
Closed via #29
