### ISSUE TITLE
index.html not able to load, 'cannot set property' bug

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/simple-data-grapher#33]
On running `https://github.com/publiclab/simple-data-grapher/blob/main/examples/index.html`,
`PublicLab.Grapher.js:188 Uncaught TypeError: Cannot set property 'first' of undefined
    at new SimpleDataGrapher (PublicLab.Grapher.js:188)
    at index.html:20`
is encountered.
![image](https://user-images.githubusercontent.com/40794215/59007745-70512d80-8845-11e9-8171-afdaff7ac32b.png)

@jywarren @namangupta01 kindly take a look at it.

**Comment by IshaGupta18** [comment]
A little help here @namangupta01 ?

**Comment by namangupta01** [comment]
@IshaGupta18 I have updated the code. Pull the new code and it will work :)
