### ISSUE TITLE
Weekly community check-in #25 (Favourite IDE) 

### ISSUE THREAD

**Issue by gauravano** [publiclab/simple-data-grapher#41]
Hi everybody :smiley: !

We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our _weekly goals and the awesome work_ we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

If you're new here, welcome, and please comment a _Hello_ below, we would love to work with you. If you're looking for new issues, please try some of our [first-timers-only](https://code.publiclab.org/#r=all) issues.

We're SO EXCITED to have your help!

**Is there anything, you would like to share with us from past week's work? What is your plan for this week?**

If you have not planned yet, just leave a Hello! :wave: so that we know that you are in sync with us :arrows_clockwise: and doing well!

The coming weeks will be full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:!!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. :raised_hands:

#### Gitter

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up [there](https://gitter.im/publiclab/publiclab) for these updates or just to join the conversation. You can also join us through http://publiclab.org/chat :speech_balloon:.

**This Week's Theme:**

Share about your favourite IDE and what makes it special. Also, if you don't have anyone favourite mention the ones you like and reason.
 

You can find our list of previous check-ins [here](https://github.com/publiclab/plots2/issues/5627) 

## Note to Summer of Code interns:

Hi, we request all the SoC students to include the below-mentioned points in their check-in comment:
- FTOs created in the previous week
- Progress for your project
- Upcoming week's goals 
- PR reviewed by you in the previous week
- Work completed last week.
- What things you did collaboratively last week? This is really important we want team spirit.
It is like a weekly scrum. Be flexible. 
- Feel free to tell us about your absence too, if you're taking a break.
- Issue/PR you're struggling with (if any)

With FTOs and PR reviews, we are seeking to develop a much more friendly and collaborative platform. We want you all will involve people in your project. You all will develop skills like leadership along the way.

Thank you!

**Comment by gauravano** [comment]
**ANNOUNCEMENT by @ebarry:**
Hi all, I can repost this when someone opens our this week check-in but here for now:

Welcoming reminder that tomorrow we will convene for the 2nd Edition of Code Open Call!

Time: Jun 11, 2019 12:30 ET / 16:30 UK / 22:00 India

Link: https://zoom.us/j/440795826

Notes will be here: https://pad.publiclab.org/p/opencall (use the upper right hand button to add your name and choose your color!)

We may experiment with Zoom Breakout rooms for each project to have a small meeting simultaneously.

**Comment by gauravano** [comment]
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @IgorWilbert @vrk99 @pdurbin @HarshKhandeparkar @aashna27

**Comment by gauravano** [comment]
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @IgorWilbert @vrk99 @pdurbin @HarshKhandeparkar @niravasher @marieram @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16

**Comment by gauravano** [comment]
@publiclab/community-reps @subhahu123 @An0u @Jaya738 @mgroovyank @shreyateeza @TANGL3SIT3S @nazeem1988 @karunagoyalk @Nirvikalpa108 @cassianoblonski @EngrEric @Anjalizi @GettyOrawo @coderbeetle @corbettbw @govindjeevan @gautamig54 @daddyjab @emestabillo @letnewKid @srujana121 @jazdao @ChinwenduSilvia @aggarwal19 @Jenniline @madelinejones @helenatxu @richa031 @fabsar @kuja24 @megha070 @Aarabhi2017 @Manvi07 @siddhishree @Julius26 @VinneyJ @sonali9696 @rarrunategu1 @coreytegeler @labseven @milomacphail @CleverFool77 @ananyaarun @ananya @publiclab-mimi @shubhi2000

**Comment by gauravano** [comment]
@Priyak5 @techchic @ananya @hc-barker @edwd42 @PritiShaw @themonster2015 @supriya-kotturu @AnthoniaOkafor @scheleon @mahmodHammad @santushk @jillpena @stoic-plus @starkblaze01 @aSquare14 @vaarigupta @alonpeer @madeofhuman @ibnjunaid @aashna27 @harshithpabbati @mmmelissa @rarrunategu1 @daz @UNnamed66 @GauravJ3 @Greg-Tarr @Sanscripter @hodbadger @alaxalves @becomingajunior @monsij @vrk99 @pdurbin @HarshKhandeparkar @aashna27 @harshithpabbati @CleverFool77 @niravasher @gautamig54 @jesus-montano @michelelong @cryptoclidus

**Comment by jywarren** [comment]
Hi all! Just a heads up to @kaustubh-nair @alaxalves @stefannibrasil @cesswairimu @sashadev-sky about this great post by Mo Langmuir testing out MapKnitter! https://publiclab.org/notes/molangmuir10/06-10-2019/mapknitter-ui-evaluation

**Comment by jywarren** [comment]
Also, just repeating what @ebarry noted in the last check-in --

> Hi all, I can repost this when someone opens our this week check-in but here for now:

> Welcoming reminder that tomorrow we will convene for the 2nd Edition of Code Open Call!

> Time: Jun 11, 2019 12:30 ET / 16:30 UK / 22:00 India

> Link: https://zoom.us/j/440795826

> Notes will be here: https://pad.publiclab.org/p/opencall (use the upper right hand button to add your name and choose your color!)

> We may experiment with Zoom Breakout rooms for each project to have a small meeting simultaneously.

**Comment by jywarren** [comment]
@rexagod great demos in last week's update! I forked both your repos to @publiclab and made you an admin. Did you want to create `gh-pages` branches and link to any demos from the new forks?

**Comment by ryzokuken** [comment]
I like VSCode because it has a great plugin for Vim keybindings (cannot live without those) but still the amazing plugin ecosystem.

So yes, I like Vim's keybindings but VSCode's ecosystem. If you're mostly doing Rails though, you should just stick to Vim IMO. 

The folks at thoughtbot (https://thoughtbot.com/) have a ton of great Vim plugins for Rails dev.

**Comment by rexagod** [comment]
@jywarren Sure thing! I'll get to that as soon as possible. Hey, @ryzokuken! It's really nice to see you chiming in here! 😄

**Comment by cesswairimu** [comment]
Hello :wave: ,

My all time editor is vim :1st_place_medal: , love the dark theme and different plugins, also the fact that it runs on the terminal so I don't have to switch between windows when running commands and code editing. 

A big thumbs up to the soc folks :tada: :tada:  ..you guys are working on interesting and cool stuff and it was great to learn more about your projects today on the call :raised_hands:.

Happy week everyone :balloon:

**Comment by cryptoclidus** [comment]
Hello,

I don't have a strict favourite IDE but I like Spyder and RStudio for hashing out ideas in python/R. Reading the comments from everyone I may have to try vim!

This week I am working on a HDR method and algorithm that will get consistent good graphs from jpgs. I had a pretty successful preliminary result here: https://spectralworkbench.org/spectrums/159819

A big question coming up is how best to connect the RPi to the computer for faster capture and processing, and access to raw RGB data rather than jpgs (maybe a socket?).

**Comment by daz** [comment]
Can we stop this mass tagging users? Very annoying

**Comment by jywarren** [comment]
Hi @daz - sorry we bothered you. We'll do our best not to tag you again but since this is a rotating responsibility it's a bit tough. What I recommend is choosing "ignore" in the `Watching` menu, just to be sure you aren't bothered again:

![image](https://user-images.githubusercontent.com/24359/59312141-fae8c100-8c79-11e9-9e3f-bf5ebc3dec22.png)

Thanks!

**Comment by jywarren** [comment]
@cryptoclidus this is a great question. I think @sidntrivedi012 is working on a stand-alone capture interface. What is possible with that working is to stream video from a Raspberry Pi as we do in Infragram:

https://publiclab.github.io/infragram/ is installed in the https://publiclab.org/wiki/pi-builder Pi Builder software, so when you start up that Raspberry Pi, you can use Infragram there (it's actually these lines copying over the image into the video stream: https://github.com/publiclab/infragram/blob/92ee1afd79652f0cf3c83dab0c1ac51f6b70c61d/pi/index.html#L185-L191)

If @sidntrivedi012 and you want to collaborate on this, it'd be a great output from the "stand-alone capture" project! https://github.com/publiclab/spectral-workbench.js/issues/56

**Comment by daz** [comment]
Yes, but then you will tag me in the next one on a different repo that I was never watching

**Comment by MargaretAN9** [comment]
Hello! I am so glad that we are doing these weekly check-ins! 😄
I made a user manual for the Image Sequencer so that anyone can find it easy to use.  Version 0.1 of the Image Sequencer User Manual is available at: https://github.com/MargaretAN9/GSOC-2019/blob/master/Image%20Sequencer%20User%20Manual%20v3.docx select 'view raw' for Word file download.

**Comment by cryptoclidus** [comment]
@jywarren and @sidntrivedi012 a standalone capture interface sounds wonderful. Sure if you don't mind it would be great to collaborate!

**Comment by rexagod** [comment]
> Yes, but then you will tag me in the next one on a different repo that I was never watching

Hey @daz! I'll make sure you aren't included in the check-ins from here on out. Thank you for cooperating with us.
***
@gauravano Remember a while back when someone suggested running scripts in the console like some orgs do currently but we weren't in the favour of it? I guess we should re-evaluate on that decision and start planning on forming an elaborate script including things like, 
```
if(document.body.innerText.match(/daz/)){alert('...');}
```
What do you think?

**Comment by rexagod** [comment]
Better yet, make an md file and add names to it? You know, of the people that don't want to be included? Or maybe removing those names from our database of users?

**Comment by daz** [comment]
No, just stop abusing the tagging system. Let people opt in to a subscription.

**Comment by HarshKhandeparkar** [comment]
Hello @daz, people cannot subscribe to all repos. Even if they do, they will get notifs about all the activity in those repos. I personally love this system of tagging, you tag the people, they get notif only for the checkin and then done.

If you(or anyone else) doesn't want to get notified, please let us know and we will stop tagging you.

**Comment by HarshKhandeparkar** [comment]
Sorry for the inconvenience.

**Comment by namangupta01** [comment]
Hi all, My favourite IDE is WebStorm for javascript projects and RubyMine for Ruby Projects. 

I have been working on different things from organizing the structure and dividing code into MVC using classes and also to support multiple graphs in simple-data-grapher in pr https://github.com/publiclab/simple-data-grapher/pull/36 to WebSocket basic implementation  in plots2 in pr https://github.com/publiclab/plots2/pull/5744 to solving looping bug in reply-by-email feature in pr https://github.com/publiclab/plots2/pull/5897.

This week I am going to work on reviewing Isha's pr, Get Basic Implementation of WebSocket Merged 
and work on the next step for ActionCable part.

**Comment by sidntrivedi012** [comment]
Hey everyone, I personally use VSCode for all of the stuff I do with javascript. Also, I use the awesome extensions like ESLint and Night-owl theme(https://marketplace.visualstudio.com/items?itemName=sdras.night-owl) to make the dev-environment more efficient and appealing .

This week, I will be working on https://github.com/publiclab/spectral-workbench.js/issues/95 and also on refactoring the capture.js file (https://github.com/publiclab/spectral-workbench.js/blob/main/examples/capture/capture.js) .

@cryptoclidus So awesome that you find the idea wonderful. Would love to collaborate with you on the project. Thanks 🎉

**Comment by HarshKhandeparkar** [comment]
My favorite IDE for JS is VSCode. If I do pure JS or React, I use VSCode. I use Atom for normal Web Development i.e HTML, CSS, little bit of JS, I also use it for BASH.

VSCode:
- Has intellisense (I love this)
- Is light
- Starts up quickly
- Has a good terminal
- Awesome code completion for JS
- Perfect Marketplace

Atom:
- Good for HTML, CSS but not so much for JS.
- The best git VCS tab I have ever used. (Can even undo commits with a single click)
- Nostalgia

Packages I Use:
#### VSCode
**COLOR THEME**: [Monokai++](https://marketplace.visualstudio.com/items?itemName=dcasella.monokai-plusplus)
**Icon Theme**: [Material Icon Theme(based on google's material design)](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)
- [Save Typing(Autosave)](https://marketplace.visualstudio.com/items?itemName=akhail.save-typing)
- [Github Markdown Preview](https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview)
- [Markdown Checkboxes](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox)
- [Markdown Emoji](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji)

**Comment by SidharthBansal** [comment]
I used Atom. Now I am getting fond of Intellij. There are more features there. :-)

**Comment by kaustubh-nair** [comment]
Hey everyone :wave: 
I like vim since it can be really fast once you get a hang of it. Personally, I'm much more productive on vim than other modern gui based editors. And it has cool plugins like fuzzy search and easymotion.
### Soc update
I'm done with the Yarn switch, and also fixed asset precompilation on travis. It is ready for a merge https://github.com/publiclab/mapknitter/pull/702
@alaxalves and I are currently working  on Rails 5 upgrade https://github.com/publiclab/mapknitter/pull/685 but we're completely stuck on trying to get the database setup/migrations running. We'd really appreciate some a little help there!
Thanks!

**Comment by jywarren** [comment]
Hi everyone! I'm scrambling a bit today because of our new Kickstarter launch (https://www.kickstarter.com/projects/publiclab/babylegs/) but will catch up as I can. 

Was someone interested in opening a new weekly check-in?

**Comment by gauravano** [comment]
Really nice document @MargaretAN9 :100: :rocket:. 

@rexagod, @jywarren and I were discussing to utilize GitHub API for the contributor list like we show recent contributors on https://code.publiclab.org. Although it's not working right now, there's an issue open - https://github.com/publiclab/community-toolbox/issues/222 and, next we will try to improve that list maybe by providing options to choose a time period. Till then, let's try to filter out names on our own.

Thanks everyone for the updates!!

**Comment by MargaretAN9** [comment]
Hello and Happy Tuesday! 😄
[Here](file:///C:/Users/Marga/Downloads/opencv%20image%20sequencer%20v2.pdf) is my status update for this past week.  I am using webstorm to try and work with image sequencer @aashna27 but the javascript files keep giving me a 'throw.err' whenever I try to run them.  I have done everything I can possibly think of with node.js and npm to try and get it to work, but nothing does the trick.  Any advice?  @jywarren

**Comment by IshaGupta18** [comment]
Hello Everyone! Really great to see a check-in in this new repo!
I used to use Sublime text a lot, but recently I have shifted to VS Code and I absolutely love it

GSoC Update:

So in the last week, I completed a big PR on modularizing the code and adding more import options like a remote file and a published Google Sheet.
I have also implemented a feature to download the imported data as an Excel file using SheetJs.
I have also completed a PR on linting to implement ESlint in our project.

Both these PRs are reviewed and ready to merge! 
https://github.com/publiclab/simple-data-grapher/pull/43
https://github.com/publiclab/simple-data-grapher/pull/37

Once these 2 PRs are merged, we will have substantial code to create FTOs.
This week I will be creating at least 2 FTOs.

Currently, I am working on testing, and deciding the best framework for it. As of now, we are dealing with Mocha, but we might consider switching to Jest. https://github.com/publiclab/simple-data-grapher/issues/49

We are also having a discussion about switching to Plotly: https://github.com/publiclab/simple-data-grapher/issues/34

I will also be implementing an export option (either it will export the data or display an analysis of it) 

https://github.com/publiclab/simple-data-grapher/issues/17

I would really appreciate if the mentors can help speed up the decision-making process in testing and plotly especially.

cc: @jywarren @gauravano @IgorWilbert @Souravirus @namangupta01

**Comment by sashadev-sky** [comment]
Looks like we might of skipped a check-in and people continued on this one?@alexalves offered to open the next one on Sunday so we’ll have a new one then! 

@jywarren @gauravano

**Comment by jywarren** [comment]
Yeah, that sounds good! Thank you!

**Comment by gauravano** [comment]
Hi everyone, 

Sorry, I was not able to respond to many threads in the past 2 weeks due to the US trip. But, yeah, the US trip was great. Learned a lot at GCI summit. And, it was a pleasure meeting @jywarren @bronwen9 @sashadev-sky Amanda in-person. Would publish a blog post soon.

Hey @MargaretAN9, please open an issue with more details in https://github.com/publiclab/image-sequencer/. And, as usual, great and well-documented update!! 

Hey @IshaGupta18, looks like those ready PRs are eventually merged (great!!). Regarding the testing framework, let's start with Jest. 
Also, great community development steps around the repo. Can you also add more to Readme?

Thanks!!

**Comment by HarshKhandeparkar** [comment]
I was fiddling with animations. Created something really weird and felt like sharing.


![much-weirder](https://user-images.githubusercontent.com/34770591/59978171-37f87000-95f7-11e9-90a5-a3584ea40a8e.gif)

![even-more-weird](https://user-images.githubusercontent.com/34770591/59978182-59595c00-95f7-11e9-8023-7419f89b5065.gif)

**Comment by Rishabh570** [comment]
Hi everyone, _VS Code_ **+** _Extensions_  **===**  _Best experience_ :smiley:!

This week I'm **working** on,
- Making the recent contributors logic flexible for various time periods,
- Generating a list of FTO issue authors,
- Incorporating permalinks to site.

Work **ready** for review,
- Theme switcher,
- Implementation of the stale issues list

Work **completed**,
- The default welcome page now sources from a configuration file and is flexible to any user/organization now.
- Dropdown for navigation around repositories.

Thanks and have a great week ahead!!! :tada: :rocket: :smiley:

**Comment by alaxalves** [comment]
> Looks like we might of skipped a check-in and people continued on this one?@alaxalves offered to open the next one on Sunday so we’ll have a new one then!
> 
> @jywarren @gauravano

Oh my, I have totally forgot about that. Do we still want that?

These past weeks I have been fully working on the Rails upgrade and its patches. You can find all of my work on [publiclab/mapknitter/685](https://github.com/publiclab/mapknitter/pull/685).

**Completed** work so far: 
- Removed deprecated method invokations, such as `atr_acessible`.
- Locked every version of our gems, to latest possible.
- Fixed broken CI pipelines(Unit tests and docker building).
- Fixed the MySQL adapter integration, (had a huge help of @sashadev-sky).
- Started using strong_params.
- Started making model associations "_weak_".
- Included abstracted classes for ApplicationMailer and ApplicationRecord.
- Using `required_relative` in favor of plain `require`.
- @kaustubh-nair has done the Yarn switch, assets are precompiling successfully now.

**What's left** to do:
- Remove a few deprecation warnings.
- Fix a couple of controller tests.
- Change folder names to newest conventions.
- Investigate the simplecov integration.

@kaustubh-nair Do you remember anything else that's left?

**Comment by cesswairimu** [comment]
Hey @alaxalves, yes, please open a new check-in. Thanks

**Comment by sashadev-sky** [comment]
new check-in is in plots2 this week: https://github.com/publiclab/plots2/issues/5943
