### ISSUE TITLE
Removing unused code

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/simple-data-grapher#68]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem

Some of the code which was previously written is not required anymore.

### 📋Solution

Remove 
`<button type="button" class="btn btn-success" id=' + this.gsheetId + '> Export as Google </button><div class="g-signin2" data-onsuccess=' + this.onSignIn + '></div>` at line 
https://github.com/publiclab/simple-data-grapher/blob/fa222a480c402d15d260f70cb42c23694577e603/src/View.js#L347

and 

https://github.com/publiclab/simple-data-grapher/blob/fa222a480c402d15d260f70cb42c23694577e603/src/View.js#L113-L115

in https://github.com/publiclab/simple-data-grapher/blob/main/src/View.js

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by noah56** [comment]
Hi! I'm new to GitHub but would like to start contributing to some open source projects. I have removed the lines from Vew.js. Do I also need to remove the "<button type="button" class=..." from some other file?

**Comment by IshaGupta18** [comment]
No this one only, can you create a PR for this? Thanks a lot!

**Comment by gaddeharsha13** [comment]
Hi is this still open? Can I claim this issue?

**Comment by IshaGupta18** [comment]
Yes, please go ahead!

**Comment by sianlouisa** [comment]
Hi, I'd like to work on this if it isn't currently in progress? Thanks!

**Comment by IshaGupta18** [comment]
Yes go ahead!

**Comment by dsuarezlogans** [comment]
Hello! is still available to work on? I'm first timer and I'll like to start with this Issue

**Comment by IshaGupta18** [comment]
I think someone is working on it already?

**Comment by futuregit** [comment]
@IshaGupta18 Hello. First-timer. I see someone is working on it already. I would like to contribute, but I'm not sure where to start?

**Comment by skathuria29** [comment]
Hi!  Is this issue still up for grabs ?

**Comment by IshaGupta18** [comment]
If there is no PR for it, go for it!

**Comment by anuk79** [comment]
@IshaGupta18 Hi, if no one is working on this, can I pick this up?

**Comment by IshaGupta18** [comment]
If there is no PR, go for it!

**Comment by anuk79** [comment]
One pr has already been merged, so this issue can be closed I guess.
