### ISSUE TITLE
Remove unnecessary console.log statements

### ISSUE THREAD

**Issue by debck** [publiclab/simple-data-grapher#97]
Please Note:  **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

**Problem**
There are a lot of unnecessary `console.log` statements defined inside all the javascript functions
 in `src` folder.

**Expected behavior**

We should remove all of those console statements 

**Link to file**

You can find all the files https://github.com/publiclab/simple-data-grapher/tree/main/src

**Comment by debck** [comment]
**Uploaded on GCI dashboard**

**Comment by dungeonaltaf** [comment]
I am not taking part in GCI.
Can i do this?

**Comment by debck** [comment]
Sorry, @dungeonaltaf   
This issue is reserved for the GCI students.  Please check out https://code.publiclab.org to find more issues.
Thank you

**Comment by SidharthBansal** [comment]
Published

**Comment by debck** [comment]
@SidharthBansal  Can you please recheck? It is not yet published on the dashboard

**Comment by SidharthBansal** [comment]
Please hide unwanted comments. There was latency conflicts.

**Comment by SidharthBansal** [comment]
Published now

**Comment by genesis331** [comment]
Claimed.

**Comment by debck** [comment]
hey, @genesis331 You need to complete the Installation task before moving on to the next issue. So you need to claim them on the GCI task list first and then move on to solving rest. This is a compulsion for all students. 
Have a read here: https://github.com/publiclab/plots2/issues/6808
