### ISSUE TITLE
Setup Travis CI in the project

### ISSUE THREAD

**Issue by debck** [publiclab/simple-data-grapher#98]
Please Note:  **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

**What's the feature request? Please describe.**

Travis CI makes developing software efficient and it ensures we deploy clean code that follows good practice and also detects if there are possible bugs or deficits in our code caused by a change or refactor in our project.

**Describe the solution you'd like**

So we should set up Travis CI in this project by creating a file `.travis.yml` in the root directory with proper configuration.

**Additional context**

This service simply means to automate the process by running test cases each time a new commit is pushed.

Thank You 😊

**Comment by debck** [comment]
**Uploaded on GCI dashboard**

**Comment by SidharthBansal** [comment]
Published

**Comment by Uzay-G** [comment]
Hey @debck, I would like to work on this when my other task is approved. When it is, I will test the Travis CI on my fork of the repo.

**Comment by debck** [comment]
Yes sure. You can claim this issue on GCI and then carry on the work.
